"""
Memocore Memory Extractor
Extract entities and relationships from conversations and store them in the knowledge graph.

Usage:
    from memocore.core.extractor import MemoryExtractor
    extractor = MemoryExtractor()
    await extractor.extract_and_store(conversation="...", agent_id="my_agent")
"""

import asyncio
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

from graphiti_core.nodes import EpisodeType

from memocore.agents.registry import get_profile, get_entity_types
from memocore.core.config import get_neo4j_config
from memocore.core.graphiti_factory import build_graphiti


class MemoryExtractor:
    """
    Memory Extractor — receives conversation text, extracts entities+relations,
    and writes them to the knowledge graph via Graphiti.
    """

    def __init__(
        self,
        neo4j_uri: Optional[str] = None,
        neo4j_user: Optional[str] = None,
        neo4j_password: Optional[str] = None,
    ):
        cfg = get_neo4j_config()
        self.neo4j_uri = neo4j_uri or cfg["uri"]
        self.neo4j_user = neo4j_user or cfg["user"]
        self.neo4j_password = neo4j_password or cfg["password"]
        self._graphiti = None
        self._init_lock = asyncio.Lock()

    async def _get_graphiti(self):
        async with self._init_lock:
            if self._graphiti is None:
                self._graphiti = await build_graphiti(
                    uri=self.neo4j_uri,
                    user=self.neo4j_user,
                    password=self.neo4j_password,
                    build_indices=True,
                )
        return self._graphiti

    async def extract_and_store(
        self,
        conversation: str,
        agent_id: str = "default",
        source_description: str = "conversation",
        episode_name: Optional[str] = None,
        reference_time: Optional[datetime] = None,
        group_id: Optional[str] = None,
    ) -> dict:
        """
        Core method: extract conversation content and write to knowledge graph

        Args:
            conversation: conversation text (can be the full session content)
            agent_id: Agent identifier, used for profile loading and default group_id
            source_description: data source description
            episode_name: name for this episode (auto-generated by default)
            reference_time: reference time (defaults to current time)
            group_id: Neo4j namespace (overrides agent_id when explicitly provided)
                      personal scope: pass agent_id (default)
                      team scope:     pass "team:{team_id}"
                      org scope:      pass "org:{tenant_id}"

        Returns:
            {success: bool, episode_name: str, entities_extracted: int, error: str}
        """
        if not conversation or not conversation.strip():
            return {"success": False, "error": "Empty conversation"}

        # privacy filtering (pre-write scan)
        from memocore.core.privacy import get_filter
        privacy_filter = get_filter()
        conversation, privacy_report = await privacy_filter.process_async(conversation)
        if privacy_report.should_skip:
            return {
                "success": False,
                "error": f"Privacy filter skip: {privacy_report.skip_reason}",
                "privacy_skip": True,
            }

        if episode_name is None:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            uid = uuid.uuid4().hex[:8]
            episode_name = f"{agent_id}_{ts}_{uid}"

        if reference_time is None:
            reference_time = datetime.now(timezone.utc)

        try:
            graphiti = await self._get_graphiti()

            # load extraction instructions and entity types from agent profile
            profile = get_profile(agent_id)
            entity_types = get_entity_types(agent_id)
            extraction_instructions = profile.get("extraction_instructions", "")

            effective_group_id = group_id if group_id else agent_id
            result = await graphiti.add_episode(
                name=episode_name,
                episode_body=conversation,
                source_description=source_description,
                reference_time=reference_time,
                source=EpisodeType.message,
                group_id=effective_group_id,
                entity_types=entity_types,
                custom_extraction_instructions=extraction_instructions,
            )

            # count extracted entities
            entities_count = len(result.nodes) if hasattr(result, 'nodes') else 0

            return {
                "success": True,
                "episode_name": episode_name,
                "entities_extracted": entities_count,
                "group_id": effective_group_id,
            }

        except Exception as e:
            return {
                "success": False,
                "episode_name": episode_name,
                "error": str(e),
            }

    async def close(self):
        if self._graphiti:
            await self._graphiti.close()
            self._graphiti = None


# ─── convenience function (for direct hook use) ────────────────────────────────

async def extract_and_store(
    conversation: str,
    agent_id: str = "default",
    source_description: str = "conversation",
    episode_name: Optional[str] = None,
    reference_time: Optional[datetime] = None,
    group_id: Optional[str] = None,
) -> dict:
    """
    Convenience function that manages extractor lifecycle automatically.
    Suitable for direct use in hooks and scripts.
    """
    extractor = MemoryExtractor()
    try:
        result = await extractor.extract_and_store(
            conversation=conversation,
            agent_id=agent_id,
            source_description=source_description,
            episode_name=episode_name,
            reference_time=reference_time,
            group_id=group_id,
        )
        return result
    finally:
        await extractor.close()


if __name__ == "__main__":
    # Quick test
    test_conv = """
    User: Have we decided on the tech stack?
    Assistant: Confirmed: Graphiti + Neo4j. Neo4j is already running locally.
    User: Good. Also remember, all output files must be saved to cloud storage, not just links.
    Assistant: Got it. Files will go to the shared inbox folder.
    User: Right. And notifications should go via direct message, not group chat.
    """

    async def run():
        result = await extract_and_store(
            conversation=test_conv,
            source_description="extractor test",
        )
        print("Result:", result)

    asyncio.run(run())
